### ISSUE TITLE
Deploy script broke

### ISSUE THREAD

**Issue by simonw** [natbat/rockybeaches#69]

**Comment by simonw** [comment]
First problem was with an Airtable API key. Fixed that by removing the Airtable export.

**Comment by simonw** [comment]
https://github.com/natbat/rockybeaches/actions/runs/5800364816/job/15722326210
```
Traceback (most recent call last):
  File "fetch_inaturalist.py", line 37, in <module>
    for species_count in fetch_species_counts(place):
  File "fetch_inaturalist.py", line 16, in fetch_species_counts
    return httpx.get(url).json()["results"]
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
```

**Comment by simonw** [comment]
HTTPX default timeout is 5s https://www.python-httpx.org/advanced/#timeout-configuration

**Comment by simonw** [comment]
https://github.com/natbat/rockybeaches/blob/e91feead884b525b685bd22b5392e4ea7ab18109/fetch_inaturalist.py#L7-L16

https://github.com/natbat/rockybeaches/blob/e91feead884b525b685bd22b5392e4ea7ab18109/data/stations.yml#L1-L5

Using default radius 0.5

**Comment by simonw** [comment]
https://api.inaturalist.org/v1/observations/species_counts?quality_grade=research&lat=37.4954239229958&lng=-122.4986519292&radius=0.5 works but is a bit slow - I'll knock timeout up to 20s.

**Comment by simonw** [comment]
Fixed: https://www.rockybeaches.com/us/pillar-point
